default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lunch_and_learn_development
test:
  <<: *default
  database: lunch_and_learn_test

production:
  <<: *default
  database: lunch_and_learn_production
  username: lunch_and_learn
  password: <%= ENV['LUNCH_AND_LEARN_DATABASE_PASSWORD'] %>
