name: Ruby on Rails CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: lunch_and_learn_test
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ruby and dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
          bundler-version: 2.2.11
          bundler-cache: true
      - name: Install Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install packages with Yarn
        run: yarn install
      - name: Setup environment variables
        run: |
          echo "RAILS_ENV=test" >> $GITHUB_ENV
          echo "DATABASE_URL=postgres://postgres:password@localhost:5432/app_test" >> $GITHUB_ENV
      - name: Create database
        run: rails db:create
      - name: Run database migrations
        run: rails db:migrate
      - name: Run tests
        run: bundle exec rspec
